language: r
r: 
  - bioc-release
  - bioc-devel
bioc_check: true
sudo: required
warnings_are_errors: false
cache: packages

r_packages:
  - covr
  - devtools

after_success:
  - Rscript -e 'library(covr); codecov()'
